### ISSUE TITLE
Provider not working when temporal frontend has TLS enabled

### ISSUE THREAD

**Issue by mihaelabalas84** [denniskniep/provider-temporal#7]
### What problem are you facing?
Provider temporal is not able to connect to temporal frontend when it has TLS enabled.

### How could Crossplane help solve your problem?
Add optional TLS configuration parameters and connection support.

**Comment by denniskniep** [comment]
Released [here](https://github.com/denniskniep/provider-temporal/releases/tag/v1.5.0)
